--- #YAML:1.0
name:                Catalyst-Plugin-CookiedSession
version:             0.34
abstract:            Store sessions in a browser cookie
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst::Exception:           0
    Class::Accessor::Fast:         0
    Crypt::CBC:                    0
    Crypt::Rijndael:               0
    JSON::XS::VersionOneAndTwo:    0
    MIME::Base64:                  0
    NEXT:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
